[build]
  command = "cp src/api.js ./"
  publish = "tmp"
  functions = "."

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs10.x"

[template.environment]
  JWT_SECRET = "JWT Secret for decoding auth information"
  AIRTABLE_API_KEY = "Airtable API key from airtable.com/account"
  AIRTABLE_BASE_ID = "Airtable Base ID from airtable.com/api"
