[build]
  command = "cp src/api.js ./"
  publish = "dist"
  functions = "."

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs10.x"

[template.environment]
  AIRTABLE_API_KEY = "Airtable API key from airtable.com/account"
  AIRTABLE_BASE_ID = "Airtable Base ID from airtable.com/api"
  AIRTABLE_OWNER_TABLE_NAME = "Airtable \"Owner\" Table name for authorizing your app users"
  JWT_SECRET = "JWT Secret for decoding auth information"
